/**
 * Supabase — Auto-generated Database Types
 *
 * Run `pnpm db:types` to regenerate from your Supabase schema.
 * Do NOT edit this file manually.
 */

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
